apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: arm64-nodepool
spec:
  template:
    spec:
      nodeClassRef:
        name: arm64-ec2nodeclass
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: ["arm64"]
        - key: "karpenter.k8s.aws/instance-category"
          operator: In
          values: ["t", c", "m", "r"]
        - key: "karpenter.k8s.aws/instance-cpu"
          operator: In
          values: ["4", "8", "16", "32"]
        - key: "karpenter.k8s.aws/instance-hypervisor"
          operator: In
          values: ["nitro"]
        - key: "karpenter.k8s.aws/instance-generation"
          operator: Gt
          values: ["2"]
  limits:
    cpu: 1000
  disruption:
    consolidationPolicy: WhenEmpty
    consolidateAfter: 30s
