apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: arm64-ec2nodeclass
spec:
  amiFamily: AL2023
  role: ${KARPENTER_NODE_IAM_ROLE_NAME} #Karpenter-ex-codium-ai-20240706201736603900000018 #${module.karpenter.node_iam_role_name}
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: ${CLUSTER_NAME} #codiumai-challenge
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: ${CLUSTER_NAME} #${module.eks.cluster_name}
  tags:
    karpenter.sh/discovery: ${CLUSTER_NAME} #${module.eks.cluster_name}
