apiVersion: apps/v1
kind: Deployment
metadata:
  name: arm64inflate
spec:
  replicas: 0
  selector:
    matchLabels:
      app: arm64inflate
  template:
    metadata:
      labels:
        app: arm64inflate
    spec:
      nodeSelector:
        kubernetes.io/arch: arm64 # Ensure pods run on ARM64 nodes
      containers:
        - name: arm64inflate
          image: public.ecr.aws/eks-distro/kubernetes/pause:3.7
          resources:
            requests:
              cpu: 1